# SPDX-License-Identifier: Apache-2.0
# Copyright © 2019 Intel Corporation

---

- name: create directory for ngc configs
  file:
    name: "{{ configs_dest }}/ngc"
    state: directory

- name: Synchronize epcforedge sources
  block:
    - name: copy sources
      synchronize:
        src: "{{ playbook_dir }}/../epcforedge"
        dest: "{{ _sync_sources_dest }}/../"
      delegate_to: localhost
      when: always_copy_sources

