# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

---

- name: Generate ZMQ keys for {{ app_name }}
  command: /usr/bin/python3 etcd_zmq_key.py {{ app_name }}
  environment:
    ETCDCTL_CACERT: "{{ rootca_cert }}"
    ETCDCTL_CERT: "{{ root_client_cert }}"
    ETCDCTL_KEY: "{{ root_client_key }}"
  args:
      chdir: "{{ eis_integ_path }}"
  changed_when: true
  when: zmq_keys_gen_force == false

- name: Force generate ZMQ keys for {{ app_name }}
  command: /usr/bin/python3 etcd_zmq_key.py {{ app_name }} --force
  environment:
    ETCDCTL_CACERT: "{{ rootca_cert }}"
    ETCDCTL_CERT: "{{ root_client_cert }}"
    ETCDCTL_KEY: "{{ root_client_key }}"
  args:
      chdir: "{{ eis_integ_path }}"
  changed_when: true
  when: zmq_keys_gen_force == true
