# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

---

# Stop nfd-worker container
- name: remove nfd-worker container
  docker_container:
    name: "{{ _nfd_worker_container_name }}"
    state: absent

- name: create temp directory
  tempfile:
    state: directory
    suffix: .nfd-worker
  register: tmp_dir

- name: copy docker-compose.yml file
  copy:
    src: docker-compose.yml
    dest: "{{ tmp_dir.path }}"

# Bring up nfd-worker container
- name: bring up nfd-worker container
  command: docker-compose up -d --no-build
  args:
    chdir: "{{ tmp_dir.path }}"
  environment:
    CONTAINER_NAME: "{{ _nfd_worker_container_name }}"
    VER: "{{ _nfd_version }}"
    CERTS_DIR: "{{ _certs_dest }}"
    ENDPOINT: "{{ _nfd_master_endpoint }}"
    NODEID: "{{ node_add_response.json.id }}"
    INTERVAL: "{{ _nfd_update_interval }}"
  changed_when: true

- name: remove temp directory
  file:
    path: "{{ tmp_dir.path }}"
    state: absent
  when: tmp_dir.path is defined
