# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

---

- name: check if host is controller
  debug:
    msg: "NFD Master is only for controller host"
  when: "'controller_group' not in group_names"

- include_tasks: nfd.yml
  when: "'controller_group' in group_names"
