# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

---

- name: NFD master firewall rule
  ignore_errors: yes
  firewalld:
    port: 8082/tcp
    permanent: yes
    state: enabled
    immediate: yes

- name: reload firewall rules
  command: firewall-cmd --reload
  changed_when: false

- name: build NFD master image
  block:
  - name: create temporary custom .openness_gitconfig
    include_tasks: ../../../sync_sources/tasks/gitconfig_bootstrap.yml
  - name: build NFD master binary
    shell: source /etc/profile && go build -o dist/nfd-master ./cmd/nfd-master
    args:
      chdir: "{{ _sync_sources_dest }}"
      creates: "{{ _sync_sources_dest }}/dist/nfd-master"
  - name: build Docker image
    command: docker-compose build nfd-master
    args:
      chdir: "{{ _sync_sources_dest }}"
  always:
  - name: remove temporary .openness_gitconfig
    include_tasks: ../../../sync_sources/tasks/gitconfig_remove.yml

- name: bring up NFD master
  command: docker-compose up -d --no-build nfd-master
  args:
    chdir: "{{ _sync_sources_dest }}"
  changed_when: true
