# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

# Global variables for the host [localhost]
# Will override local variables from defaults

---

### Proxy settings
# Setup proxy on the machine - required if the Internet is accessible via proxy
proxy_os_enable: true
# Clear previous proxy settings
proxy_os_remove_old: true
# Proxy URLs to be used for HTTP, HTTPS and FTP
proxy_os_http: "http://proxy.example.org:3129"
proxy_os_https: "http://proxy.example.org:3128"
proxy_os_ftp: "http://proxy.example.org:3128"
proxy_os_noproxy: ""
# Proxy to be used by YUM (/etc/yum.conf)
proxy_yum_url: "http://proxy.example.org:3128"

### EIS repository configuration
eis_source: "gitclone"      # set string  as "gitclone" or "release" 
release_package_path: ""    # provide release package archive path when eis_source set to "release"

eis_env_file: "{{ eis_sources_dir }}/build/.env"

os_yum_base_packages: "jq,vim-common,curl,yum-utils,python2-pip,wget,git,python-devel,moreutils"

docker_format_command: !unsafe 'docker images --format "{{.Repository}}:{{.Tag}}"'
build_eis_base_images: true
