# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-vas-cons-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-vas-cons-app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-vas-cons-app
    spec:
      containers:
      - name: {{ .Release.Name }}-vas-cons-app
        image: "{{ .Values.image.repository }}: {{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.pullPolicy }}
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        hostPath:
          path: /tmp
          type: Directory
