# SPDX-License-Identifier: Apache-2.0
# Copyright © 2019 Intel Corporation

- include_tasks: subtasks/bringdown_oam.yml

- include_tasks: subtasks/bringdown_nef.yml

- include_tasks: subtasks/bringdown_af.yml

- name: remove firewall rules
  include_tasks: rm_firewall_rules.yml

