# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019-2020 Intel Corporation

---

_hddl_kernel_devel: 3.10.0-957.el7.x86_64
_hddl_kernel_devel_url: http://linuxsoft.cern.ch/centos-vault/7.6.1810/os/x86_64/Packages/kernel-devel-{{ _hddl_kernel_devel }}.rpm

_openvino_name: "l_openvino_toolkit_p_2020.2.120.tgz"

_openvino_url: "http://registrationcenter-download.intel.com/akdlm/irc_nas/16612/{{ _openvino_name }}"

_openvino_download_dest: "/temp/{{ _openvino_name }}"
_openvino_download_dir: "/temp/openvino"
_openvino_silent_config: "{{ _openvino_download_dir }}/silent.cfg"
_openvino_install_command: "./install.sh -s silent.cfg"
_openvino_hddl_dependency_install: "source /opt/intel/openvino/bin/setupvars.sh && ${HDDL_INSTALL_DIR}/install_IVAD_VPU_dependencies.sh"

_docker_hddlservice_tag: "1.0"
