# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

---
# Playbook for On-Premises deployment

- hosts: controller_group

  pre_tasks:
    - name: check deployment settings
      include_tasks: ./tasks/settings_check_onprem.yml
    - name: print deployment settings
      include_tasks: ./tasks/print_vars.yml

  roles:
    - role: machine_setup/os_setup
    - role: time/ntp
      when: ntp_enable | default(False)
    - role: docker
    - role: sync_sources
    - role: golang

    - role: openness/master
    - role: nfd/master
      when: onprem_nfd_enable | default(True)
    - role: ngc_test/onprem/master
      when: epcfpredge_enable is defined
    - role: apache

- hosts: edgenode_group

  pre_tasks:
    - name: check deployment settings
      include_tasks: ./tasks/settings_check_onprem.yml
    - name: print deployment settings
      include_tasks: ./tasks/print_vars.yml

  roles:
    - role: machine_setup/os_setup
    - role: time/ntp
      when: ntp_enable | default(False)
    - role: time/verify

    - role: machine_setup/custom_kernel
      when: not (kernel_skip | default(False))
    - role: machine_setup/grub
    - role: machine_setup/configure_tuned
      when: not (tuned_skip | default(False))
    - role: machine_setup/conditional_reboot

    - role: dpdk
    - role: golang
    - role: docker
    - role: libvirt
    - role: qemu
    - role: sriov_device_init
    - role: sync_sources
    - role: interapp_ovs
      when: onprem_iac_enable | default(False)
    - role: openness/worker
    - role: hddl/worker
      when: onprem_hddl_enable | default(False)
    - role: nfd/worker
      when: onprem_nfd_enable | default(True)
