# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019-2020 Intel Corporation

---
- hosts: controller_group
  tasks:
    - name: OVNCNI cleanup
      block:
        - name: load ovn variables
          include_vars: ./roles/openness/dataplane/ovncni/common/defaults/main.yml
        - name: clean ovn
          include_tasks: ./roles/openness/dataplane/ovncni/common/tasks/cleanup.yml
      when: "'ovncni' in onprem_dataplane"

    - name: load docker variables
      include_vars: ./roles/docker/defaults/main.yml

    - name: prune docker
      include_tasks: ./roles/docker/tasks/prune.yml

    - name: uninstall docker
      include_tasks: ./roles/docker/tasks/uninstall.yml

    - name: load sync_sources variables
      include_vars: ./roles/sync_sources/defaults/main.yml

    - name: cleanup sync_sources
      include_tasks: ./roles/sync_sources/tasks/cleanup.yml

    - name: load golang variables
      include_vars: ./roles/golang/defaults/main.yml

    - name: cleanup golang
      include_tasks: ./roles/golang/tasks/cleanup.yml

- hosts: edgenode_group
  serial: 1
  tasks:
    - name: cleanup openness
      include_tasks: ./roles/openness/worker/tasks/cleanup.yml

    - name: OVNCNI cleanup
      block:
        - name: load ovn variables
          include_vars: ./roles/openness/dataplane/ovncni/common/defaults/main.yml
        - name: clean ovn
          include_tasks: ./roles/openness/dataplane/ovncni/common/tasks/cleanup.yml
      when: "'ovncni' in onprem_dataplane"

    - name: HDDL cleanup
      block:
        - name: load onprem hddl variables
          include_vars: ./roles/hddl/worker/defaults/main.yml
        - name: clean onprem hddl
          include_tasks: ./roles/hddl/worker/tasks/cleanup.yml
      when: onprem_hddl_enable | default(False)

    - name: load docker variables
      include_vars: ./roles/docker/defaults/main.yml

    - name: prune docker
      include_tasks: ./roles/docker/tasks/prune.yml

    - name: uninstall docker
      include_tasks: ./roles/docker/tasks/uninstall.yml

    - name: load golang variables
      include_vars: ./roles/golang/defaults/main.yml

    - name: cleanup golang
      include_tasks: ./roles/golang/tasks/cleanup.yml

    - name: load libvirt variables
      include_vars: ./roles/libvirt/defaults/main.yml

    - name: cleanup libvirt
      include_tasks: ./roles/libvirt/tasks/cleanup.yml

    - name: load qemu variables
      include_vars: ./roles/qemu/defaults/main.yml

    - name: cleanup qemu
      include_tasks: ./roles/qemu/tasks/cleanup.yml

    - name: load sriov defaults if not defined
      include_vars: ./roles/sriov_device_init/defaults/main.yml
      when: sriov is not defined

    - name: cleanup sriov
      include_tasks: ./roles/sriov_device_init/tasks/cleanup.yml

    - name: load dpdk variables
      include_vars: ./roles/dpdk/defaults/main.yml

    - name: cleanup dpdk
      include_tasks: ./roles/dpdk/tasks/cleanup.yml

    - name: load sync_sources variables
      include_vars: ./roles/sync_sources/defaults/main.yml

    - name: cleanup sync_sources
      include_tasks: ./roles/sync_sources/tasks/cleanup.yml
