# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

---

- name: create /var/lib/appliance/nts
  file:
    path: /var/lib/appliance/nts
    state: directory

- name: create /var/lib/appliance/nts/qemu
  file:
    path: /var/lib/appliance/nts/qemu
    state: directory
    group: kvm
    mode: g+s

- name: copy nts.cfg -> /var/lib/appliance/nts/nts.cfg
  copy:
    src: "{{ _sync_sources_dest }}/internal/nts/nts.cfg"
    dest: /var/lib/appliance/nts/nts.cfg
    remote_src: yes

- name: build NTS container
  make:
    target: nts
    chdir: "{{ _sync_sources_dest }}"
    params:
      RTE_SDK: "{{ ansible_local.dpdk._dpdk_install_dir }}"
      RTE_TARGET: "{{ _dpdk_make_target }}"

- name: remove old NTS container
  docker_container:
    name: "{{ _docker_nts_container_name }}"
    state: absent

- name: up nts container
  command: "docker-compose up --no-start --no-build nts"
  args:
    chdir: "{{ _sync_sources_dest }}"
  environment:
    VER: "{{ _docker_containers_ver }}"
    OVSE: "{{ onprem_iac_enable | default(False) }}"
    OVS_BRIDGE_NAME: "{{ _ovs_bridge_name if (onprem_iac_enable | default(False)) else ''  }}"
    NTS_MEM_MB_S0: "{{ docker_nts_mem_mb_s0 }}"
    NTS_MEM_MB_S1: "{{ docker_nts_mem_mb_s1 }}"
  changed_when: true
