# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019-2020 Intel Corporation

---

_docker_containers_ver: "1.0"
_docker_syslog_container_name: "edgenode_syslog-ng_1"
_docker_appliance_container_name: "edgenode_appliance_1"
_docker_eaa_container_name: "edgenode_eaa_1"
_docker_edgednssvr_container_name: "mec-app-edgednssvr"
_remote_syslog_ip: "{{ hostvars[groups['controller_group'][0]]['ansible_host'] }}"
_enrollment_endpoint: "{{ _remote_syslog_ip }}:8081"
_download_root_ca_from_controller: true
_gopath: "$GOPATH"
