# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

---

- name: check if host is node
  debug:
    msg: "SRIOV Device Initialization role is for Edge Nodes only"
  when: "'edgenode_group' not in group_names"

- include_tasks: cleanup.yml
  when: "'edgenode_group' in group_names"

- include_tasks: sriov_device_init.yml
  when: "'edgenode_group' in group_names"
