# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

---

_certs_dest: /var/lib/appliance/certs

_nfd_version: "v0.5.0"

_nfd_worker_container_name: "nfd-worker"
_nfd_master_ip: "{{ hostvars[groups['controller_group'][0]]['ansible_host'] }}"
_nfd_port: "8082"
_nfd_master_endpoint: "{{ _nfd_master_ip }}:{{ _nfd_port }}"
_nfd_update_interval: "300s"
