# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019-2020 Intel Corporation

---
- name: check if a backup of original .env file already exists
  stat:
    path: "{{ _sync_sources_dest }}/.env.ansible.backup"
  register: env_backup_file

- name: make a backup of original .env file if backup is missing
  copy:
    src: "{{ _sync_sources_dest }}/.env"
    dest: "{{ _sync_sources_dest }}/.env.ansible.backup"
    remote_src: yes
  when: not env_backup_file.stat.exists

- name: generate .env file
  template:
    src: .env.j2
    dest: "{{ _sync_sources_dest }}/.env"

- name: online build controller docker images
  block:
    - name: create temporary custom .openness_gitconfig
      include_tasks: ../../../sync_sources/tasks/gitconfig_bootstrap.yml
    - name: build controller docker images
      make:
        chdir: "{{ _sync_sources_dest }}"
        target: build
      register: build_controller_output
    - debug:
        msg: "{{ build_controller_output.stdout }}"
  always:
    - name: remove temporary .openness_gitconfig
      include_tasks: ../../../sync_sources/tasks/gitconfig_remove.yml

- name: start controller
  make:
    chdir: "{{ _sync_sources_dest }}"
    target: all-up
  register: start_controller_output

- name: controller start output
  debug:
    msg: "{{ start_controller_output.stdout }}"
