# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

---
apiVersion: v1
kind: Pod
metadata:
  name: openvino-prod-app
  namespace: default
spec:
  containers:
  - name: openvino-prod-app
    image: openvino-prod-app:1.0
    imagePullPolicy: Never

