# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

---

- name: Add {{ app_name }} certificates to the secrets
  command: "kubectl -n {{ k8s_eis_namespace }} create secret generic {{ app_name | lower }} --from-file=./{{ key_name }} --from-file=./{{ cert_name }}"
  args:
    chdir: "{{ etcd_certs_location }}/{{ app_name }}"
  changed_when: true
  ignore_errors: yes
