# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

---

- name: get controller's IP
  set_fact:
    _controller_ip: "{{ hostvars[groups['controller_group'][0]]['ansible_host'] }}"

- name: make an auth request
  uri:
    url: http://{{ _controller_ip }}:8080/auth
    method: POST
    body_format: json
    body:
      username: admin
      password: "{{ cce_admin_password }}"
  environment:
    HTTP_PROXY: ""
    http_proxy: ""
  register: auth_response
  failed_when: auth_response.status != 201

- name: extract auth token
  set_fact:
    auth_token: "{{ auth_response.json.token }}"

- name: get list of added nodes
  uri:
    url: http://{{ _controller_ip }}:8080/nodes
    method: GET
    headers:
      Authorization: Bearer {{ auth_token }}
  environment:
    HTTP_PROXY: ""
    http_proxy: ""
  register: added_nodes

- name: check if node is already added
  set_fact:
    node_already_added: "{{ verification_key in (added_nodes.json.nodes | map(attribute='serial')) }}"

- name: add the node if needed
  uri:
    url: http://{{ _controller_ip }}:8080/nodes
    method: POST
    body_format: json
    body:
      name: "{{ inventory_hostname }}"
      location: "{{ ansible_hostname }} ({{ ansible_host }})"
      serial: "{{ verification_key }}"
    headers:
      Authorization: Bearer {{ auth_token }}
  environment:
    HTTP_PROXY: ""
    http_proxy: ""
  register: node_add_response
  failed_when: node_add_response.status != 201
  when: not node_already_added

- name: save node ID in /etc/environment
  lineinfile:
    path: /etc/environment
    state: present
    line: "NODEID={{ node_add_response.json.id }}"
