# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019-2020 Intel Corporation

---

- name: copy files to /var/lib/appliance
  copy:
    src: "{{ _sync_sources_dest }}/configs"
    dest: /var/lib/appliance/
    directory_mode: yes
    remote_src: yes
