# SPDX-License-Identifier: Apache-2.0
# Copyright © 2020 Intel Corporation

---
- name: include common vars
  include_vars: ../../../openness/master/defaults/main.yml

- name: check if a backup of original .env file already exists
  stat:
    path: "{{ git_repo_epcforedge_dir }}/cnca/ui/.env.ansible.backup"
  register: env_backup_file

- name: make a backup of original .env file if backup is missing
  copy:
    src: "{{ git_repo_epcforedge_dir }}/cnca/ui/.env"
    dest: "{{ git_repo_epcforedge_dir }}/cnca/ui/.env.ansible.backup"
    remote_src: yes
  when: not env_backup_file.stat.exists

- name: generate .env file and copy it to the repo
  template:
    src: ../../../openness/master/templates/.env.j2
    dest: "{{ git_repo_epcforedge_dir }}/cnca/ui/.env"

- name: online build cnca UI docker images
  block:
    - name: create temporary custom .openness_gitconfig
      include_tasks: roles/sync_sources/tasks/gitconfig_bootstrap.yml
    - name: build controllers cnca docker images
      make:
        chdir: "{{ git_repo_epcforedge_dir }}/cnca/ui"
        target: build
      register: build_cnca_ui_images_output
    - debug:
        msg: "{{ build_cnca_ui_images_output.stdout }}"
  always:
    - name: remove temporary .openness_gitconfig
      include_tasks: roles/sync_sources/tasks/gitconfig_remove.yml

- name: start controllers cnca UI docker images
  make:
    chdir: "{{ git_repo_epcforedge_dir }}/cnca/ui"
    target: ui-up
  register: start_controller_images_epcforedge_output

- name: debug controller cnca images from start output
  debug:
    msg: "{{ start_controller_images_epcforedge_output.stdout }}"
