# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

---

etcd_data_host_mount_path: "{{ eis_install_path }}/etcd/tmp"

etcd_listen_client_urls: "0.0.0.0"
etcd_client_port: 2379
etcd_peer_port: 2380
etcd_certs_pod_mount_path: "/EIS/etcd/Certificates"
etcdctl_src_path: "{{ eis_integ_path }}/bin"
etcd_initial_cluster_state: "new"
etcd_initial_cluster_token: "eis-cluster"
etcd_data_dir: "{{ lookup('env', 'ETCD_DATA_DIR') }}"

app_name: etcd
pod_name: ia-etcd
docker_name: ia_etcd
helm_release_name: "etcd-release"
helm_chart_etcd: "{{ helm_charts_location }}/etcd"
