# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    name: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image }}
          volumeMounts:
            - name: etcd-data
              mountPath: {{ .Values.etcdDataDir }}
            - mountPath: {{ .Values.etcdCertsPodMountPath }}
              name: etcd-certs
              readOnly: true
          ports:
            - name: etcd-clt-port
              containerPort: {{ .Values.etcdClientPort }}
            - name: etcd-peer-port
              containerPort: {{ .Values.etcdPeerPort }}
          command: ["./etcd"]
          args:
            - "--initial-cluster-token={{ .Values.etcdInitialClusterToken }}"
            - "--initial-cluster-state={{ .Values.etcdInitialClusterState }}"
{{- if eq (default .Values.devMode "false") "true" }}
            - "--initial-cluster=default=http://{{ .Values.etcdListenClientUrls }}:{{ .Values.etcdPeerPort }}"
            - "--initial-advertise-peer-urls=http://{{ .Values.etcdListenClientUrls }}:{{ .Values.etcdPeerPort }}"
            - "--listen-peer-urls=http://{{ .Values.etcdListenClientUrls }}:{{ .Values.etcdPeerPort }}"
            - "--listen-client-urls=http://{{ .Values.etcdListenClientUrls }}:{{ .Values.etcdClientPort }}"
            - "--advertise-client-urls=http://{{ .Values.etcdListenClientUrls }}:{{ .Values.etcdClientPort }}"
{{- else }}
            - "--initial-cluster=default=https://{{ .Values.etcdListenClientUrls }}:{{ .Values.etcdPeerPort }}"
            - "--initial-advertise-peer-urls=https://{{ .Values.etcdListenClientUrls }}:{{ .Values.etcdPeerPort }}"
            - "--listen-peer-urls=https://{{ .Values.etcdListenClientUrls }}:{{ .Values.etcdPeerPort }}"
            - "--listen-client-urls=https://{{ .Values.etcdListenClientUrls }}:{{ .Values.etcdClientPort }}"
            - "--advertise-client-urls=https://{{ .Values.etcdListenClientUrls }}:{{ .Values.etcdClientPort }}"
            - "--cert-file={{ .Values.etcdCertsPodMountPath }}/tls.crt"
            - "--key-file={{ .Values.etcdCertsPodMountPath }}/tls.key"
            - "--trusted-ca-file={{ .Values.etcdCertsPodMountPath }}/{{ .Values.rootCACertName }}"
            - "--client-cert-auth=true"
            - "--peer-auto-tls=true"
            - "--data-dir={{ .Values.etcdDataDir }}"
{{- end }}

      volumes:
        - name: etcd-data
          hostPath:
            path: {{ .Values.etcdDataHostMountPath }}
        - name: etcd-certs
          projected:
            sources:
            - secret:
                name: {{ .Values.secrets.etcdCertsSecretName }}
            - secret:
                name: {{ .Values.secrets.rootCaSecretName }}

