# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019 Intel Corporation

---
- hosts: localhost
  any_errors_fatal: false
  tasks:
  - debug:
      msg: "--- BUILD IMAGES ---"
  - include_vars: ../vars/defaults.yml
  - debug:
      msg: "Base path set to: {{ my_root_path }}"

  # Tasks
  - include_tasks: ../docker/compose_build.yml
  
  # Finish
  - include_tasks: ./script_success.yml
