# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019-2020 Intel Corporation

---

- name: reload facts
  setup:

- name: build cleanup
  make:
    chdir: "{{ _sync_sources_dest }}"
    target: clean
    params:
      RTE_SDK: "{{ ansible_local.dpdk._dpdk_install_dir }}"
  when: ansible_local.dpdk._dpdk_install_dir is defined

- include_tasks: subtasks/remove_containers.yml
- include_tasks: subtasks/remove_images.yml
- include_tasks: subtasks/remove_additional_folder_structure.yml
- include_tasks: subtasks/remove_certificates_and_keys.yml
- include_tasks: subtasks/remove_docker_daemon_config_file.yml
