# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2019-2020 Intel Corporation

---

- include_tasks: subtasks/remove_containers.yml

- name: Reseting ela config
  shell: >
    set -o pipefail &&
    jq '.PCIBlacklist =  []'  {{ _sync_sources_dest }}/configs/ela.json |
    sponge {{ _sync_sources_dest }}/configs/ela.json
  args:
  changed_when: true

- include_tasks: subtasks/remove_additional_folder_structure.yml
- include_tasks: subtasks/remove_certificates_and_keys.yml
- include_tasks: subtasks/create_custom_docker_daemon_config_file.yml
