# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

---

- name: add Docker repository
  yum_repository:
    name: docker
    description: Docker CE repository
    baseurl: "{{ docker_repository_url }}"
    gpgkey: "{{ docker_repository_key }}"
    gpgcheck: yes

- name: clear yum cache
  command: yum clean all
  args:
    warn: false
  changed_when: true

- name: install Docker CE
  yum:
    name: "{{ docker_packages }}"
    state: present
  notify:
  - enable and start docker service

- name: install docker-compose
  pip:
    name: "{{ docker_compose_package }}"
    state: present

- name: set up proxy
  include_tasks: proxy.yml
  when: proxy_os_enable|bool

- name: restart services if needed
  meta: flush_handlers
