# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vas-cons-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vas-cons-app
  template:
    metadata:
      labels:
        app: vas-cons-app
    spec:
      containers:
      - name: vas-cons-app
        image: vas-cons-app:1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        hostPath:
          path: /tmp
          type: Directory
